apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol
spec:
  containers:
  - name:  myapp
    image: busybox
    args:
    - sleep
    - "3600"
    volumeMounts:
      - name: myvolume
        mountPath: "/etc/secrets"
        readOnly: true
  volumes:
  - name: myvolume
    secret:
      secretName: example-secret

