apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name:  myapp
    image: busybox
    args:
    - sleep
    - "3600"
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: example-secret
            key: db_username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: example-secret
            key: db_password

